name = "nav"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liq58FCQdQ76HY3M"
GITHUB_OWNER = "ncet86"
GITHUB_REPO = "nav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.ncetes.com/api/auth"
NEXT_PUBLIC_API_URL="https://nav.ncetes.com"

